nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.5.0.cjs

packageExtensions:
  "@mui/x-data-grid@*":
    dependencies:
      "@mui/system": "*"
  "@svgr/core@*":
    dependencies:
      "@svgr/plugin-prettier": "*"
      "@svgr/plugin-svgo": "*"
